# Generated by Django 3.1.4 on 2023-07-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(editable=False, max_length=40, unique=True),
        ),
    ]
