# Generated by Django 3.1.4 on 2023-07-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230701_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpspecialblogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_blog', to='blog.blogmodel')),
            ],
        ),
    ]
