# Generated by Django 3.1.4 on 2024-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230701_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='cover',
            field=models.FileField(null=True, upload_to='blog_cover'),
        ),
    ]
