# Generated by Django 3.1.4 on 2024-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240507_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='cover',
            field=models.ImageField(null=True, upload_to='blog_cover'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='imagelink',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
