# Generated by Django 3.1.4 on 2024-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240507_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='imagelink',
            field=models.URLField(),
        ),
    ]
